export const MOVEMENT_CREATE = "MOVEMENT_CREATE";
export const MOVEMENT_GET_LIST = "MOVEMENT_GET_LIST";
export const MOVEMENT_UPDATE_STATUS = "MOVEMENT_UPDATE_STATUS";

export const MOVEMENT_SUCCESS = "MOVEMENT_SUCCESS";
export const MOVEMENT_DATA = "MOVEMENT_DATA";
export const MOVEMENT_ERROR = "MOVEMENT_ERROR";
